
services:
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 5

  api:
    build: .
    restart: unless-stopped
    environment:
      - OLLAMA_URL=http://ollama:11434
      - EMBED_MODEL=nomic-embed-text
      - LLM_MODEL=llama3.2
      - RERANK_MODEL=BAAI/bge-reranker-base
      - DATA_DIR=/app/data
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000

volumes:
  ollama:
